name: Nodejs Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Clone repository and Setup Github
       uses: actions/checkout@v3
     - name: Nodejs Install
       uses: actions/setup-node@v3
     - name: Install Node Modules
       run: npm install
     - name: Commit changes
       uses: stefanzweifel/git-auto-commit-action@v4
       with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
     
     
    